### ISSUE TITLE
nginx vars and templates

### ISSUE THREAD

**Issue by gp187** [gov-ithub/romanescU-ansible#7]
- [x] syntax check roles/nginx/templates
   - [x] check how loops apply
   - [x] ensure config validity 
- [x] execution 
   - [x] install nginx via bash
   - [x] configure `nginx.conf`
   - [x] install 3 sites
     - [x] api
     - [x] www
     - [x] upstream
- [x] check sysvars in roles/nginx/defaults/main

**Comment by eXtenZy** [comment]
Finished creating and debugging ansible configuration templates.
SSL is still commented out until #10 is completed
